-- Create table for Dashboard Metas if it doesn't exist
CREATE TABLE IF NOT EXISTS dashboard_metas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipe TEXT NOT NULL,
    meta_objetivo NUMERIC NOT NULL DEFAULT 0,
    meta_realizada NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insert some sample data to visualize the chart immediately
INSERT INTO dashboard_metas (equipe, meta_objetivo, meta_realizada)
VALUES 
('Equipe Alpha', 1000, 850),
('Equipe Beta', 1200, 1300),
('Equipe Gama', 900, 450)
ON CONFLICT DO NOTHING;

-- Enable Row Level Security (RLS)
ALTER TABLE dashboard_metas ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access (adjust as needed for your auth model)
CREATE POLICY "Allow public read access" ON dashboard_metas FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON dashboard_metas FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update" ON dashboard_metas FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete" ON dashboard_metas FOR DELETE USING (auth.role() = 'authenticated');
