-- Create a table to store password hints publicly
create table if not exists public_user_hints (
  id bigint generated by default as identity primary key,
  identifier text not null, -- Stores 'matricula' or 'email'
  hint text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public_user_hints enable row level security;

-- Create Policy: Everyone can read hints (needed for the forgot password flow)
create policy "Public hints are viewable by everyone"
  on public_user_hints for select
  using ( true );

-- Create Policy: Authenticated users can insert their hint (during registration)
create policy "Users can insert their own hint"
  on public_user_hints for insert
  with check ( true ); 
