-- Execute este script no SQL Editor do Supabase para criar as tabelas necessárias

-- Tabela de Categorias
create table public.categorias (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null,
  descricao text,
  aba_pai text not null -- 'inicio' ou 'equipes'
);

-- Tabela de Links
create table public.links (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  titulo text not null,
  url text,
  categoria_id bigint references public.categorias(id) on delete cascade
);

-- Habilitar RLS (Row Level Security) - opcional, mas recomendado
alter table public.categorias enable row level security;
alter table public.links enable row level security;

-- Criar políticas de acesso (Permitir tudo para demonstração/testes)
-- Você pode restringir isso depois se quiser
create policy "Acesso total categorias" on public.categorias for all using (true) with check (true);
create policy "Acesso total links" on public.links for all using (true) with check (true);

-- Dados de Exemplo (Opcional)
insert into public.categorias (nome, descricao, aba_pai) values
('Sistemas Estaduais', 'Acesso aos principais portais', 'inicio'),
('Equipe Técnica', 'Servidores responsáveis', 'equipes');
