-- !!! ATENÇÃO: ESTE SCRIPT APAGARÁ AS TABELAS 'categorias' E 'links' !!!
-- Isso é necessário porque as tabelas atuais usam IDs do tipo UUID, mas o aplicativo foi configurado para usar Números (BigInt).
-- Este script corrige essa incompatibilidade recriando tudo do zero.

-- 1. Apagar tabelas antigas (com CASCADE para garantir que chaves estrangeiras não bloqueiem)
DROP TABLE IF EXISTS public.links CASCADE;
DROP TABLE IF EXISTS public.categorias CASCADE;

-- 2. Recriar Tabela Categorias (Com ID Numérico)
create table public.categorias (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null,
  descricao text,
  aba_pai text not null
);

-- 3. Recriar Tabela Links (Com ID Numérico e FK correta)
create table public.links (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  titulo text not null,
  url text,
  categoria_id bigint references public.categorias(id) on delete cascade
);

-- 4. Reaplicar Políticas de Segurança
alter table public.categorias enable row level security;
alter table public.links enable row level security;

create policy "Acesso total categorias" on public.categorias for all using (true) with check (true);
create policy "Acesso total links" on public.links for all using (true) with check (true);

-- 5. Inserir dados padrão
insert into public.categorias (nome, descricao, aba_pai) values
('Sistemas Estaduais', 'Acesso aos principais portais', 'inicio'),
('Equipe Técnica', 'Servidores responsáveis', 'equipes');
