-- Script de Correção (Executar no SQL Editor)

-- 1. Garantir que as tabelas existem (sem erro se já existirem)
create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null,
  descricao text,
  aba_pai text not null
);

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  titulo text not null,
  url text,
  categoria_id bigint references public.categorias(id) on delete cascade
);

-- 2. Resetar Políticas de Segurança (RLS) para garantir acesso
-- Habilitar RLS
alter table public.categorias enable row level security;
alter table public.links enable row level security;

-- Remover políticas antigas para evitar conflitos
drop policy if exists "Acesso total categorias" on public.categorias;
drop policy if exists "Acesso total links" on public.links;
drop policy if exists "Public Select" on public.categorias;
drop policy if exists "Public Select" on public.links;

-- Criar novas políticas permissivas
create policy "Acesso total categorias" on public.categorias for all using (true) with check (true);
create policy "Acesso total links" on public.links for all using (true) with check (true);

-- 3. Inserir dados apenas se as tabelas estiverem vazias
insert into public.categorias (nome, descricao, aba_pai)
select 'Sistemas Estaduais', 'Acesso aos principais portais', 'inicio'
where not exists (select 1 from public.categorias);

insert into public.categorias (nome, descricao, aba_pai)
select 'Equipe Técnica', 'Servidores responsáveis', 'equipes'
where not exists (select 1 from public.categorias where aba_pai = 'equipes');
